name: BotCi

on:
  push:
    branches:
      - master
      - develop

env:
  IMAGE_NAME: exchanger-bot
  IMAGE_TAG: v1.0

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Set image tag and build
        run: |
          if [ ${{ github.ref }} = 'refs/heads/develop' ]; then
            export IMAGE_TAG="${IMAGE_TAG}-dev"
          else
            export IMAGE_TAG="$IMAGE_TAG"
          fi
          echo "Image tag is $IMAGE_TAG"
          echo "::set-env name=IMAGE_TAG::$IMAGE_TAG"
          docker build . --tag $IMAGE_NAME:$IMAGE_TAG

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image into GitHub Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_ID
          docker push $IMAGE_ID